version: '3.8'

services:
    front_end:
        container_name: introducing_page_front_end
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - '3000:3000'
        command: npm run dev
